apiVersion: v2
name: lunar-broker
description: Lunar Internet Service Broker Helm chart
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: postgresql
    version: "~13.2.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "~18.6.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: nats
    version: "~1.1.0"
    repository: "https://nats-io.github.io/k8s/helm/charts/"
    condition: nats.enabled
